# EXCEL로 만든 인공신경망을 pytorch의 Tensor 클래스을 이용하여 만들기

In [1]:
import torch

필요한 함수의 정의하기

In [2]:
def ReLU_func(outputs):
    zero_tensor = torch.zeros(outputs.size())
    final_outputs = torch.maximum(outputs, zero_tensor)
    return final_outputs

def softmax(outputs):
    numerator = torch.exp(outputs-torch.max(outputs))
    denominator = torch.sum(numerator, dim=1).view(-1, 1)
    softmax = numerator/denominator
    return softmax

def cross_entropy(outputs, labels):
    return -torch.sum(labels * torch.log(outputs), dim=1)

Weight 값 설정하기

In [3]:
w_ih = torch.Tensor([[1, -2, 3],[-2, 5, 3]])
w_ho = torch.Tensor([[3, -2, 4], [-1, 2, 3], [2, -2, -4]])

Batch 가 3인 Input 값과 Labels 값의 입력하기

In [4]:
input = torch.Tensor([[2, 4],[0, 3],[-6, 2]])
labels = torch.Tensor([[1,0,0], [0,1,0], [0,0,1]])

L1의 활성화 함수 전의 값 구하기

In [5]:
L1 = torch.mm(input, w_ih)
print(L1)

tensor([[ -6.,  16.,  18.],
        [ -6.,  15.,   9.],
        [-10.,  22., -12.]])


ReLU의 적용하기

In [6]:
L1 = ReLU_func(L1)
print(L1)

tensor([[ 0., 16., 18.],
        [ 0., 15.,  9.],
        [ 0., 22.,  0.]])


Output 구하기

In [7]:
outputs = torch.mm(L1, w_ho)
print(outputs)

tensor([[ 20.,  -4., -24.],
        [  3.,  12.,   9.],
        [-22.,  44.,  66.]])


Softmax의 적용

In [8]:
so = softmax(outputs)
print(so)

tensor([[1.0000e+00, 3.7751e-11, 7.7811e-20],
        [1.1754e-04, 9.5246e-01, 4.7420e-02],
        [6.0546e-39, 2.7895e-10, 1.0000e+00]])


sample별로 loss 구하기

In [9]:
loss = cross_entropy(so, labels)
print(loss)

tensor([-0.0000, 0.0487, -0.0000])


최종 loss 구하기

In [10]:
loss = torch.mean(loss)
print(loss)

tensor(0.0162)


## EXCEL과 같은 답이 나오는가?

 #### 아니면 이유가 무엇인가? 


loss값이 엑셀에서와 주피터 노트북에서의 소수점의 처리 방식의 차이 때문에 소수점아래 수에서 아주 약간 차이를 보인다. 하지만, 거의 동일한 답이 나오는 것을 알 수 있다.